---
title: "NetworkHub: working with data from the STRING database"
author: 
- name: Annekathrin Ludt
  affiliation: 
  - &id1 Institute of Medical Biostatistics, Epidemiology and Informatics (IMBEI), Mainz
  email: anneludt@uni-mainz.de
- name: Federico Marini
  affiliation: 
  - *id1
  email: marinif@uni-mainz.de
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    theme: cosmo
    code_folding: show
    code_download: true
    global_numbering: true
    number_sections: false
editor_options: 
  chunk_output_type: console
bibliography: NetworkHub.bib
link-citations: true
date: "`r BiocStyle::doc_date()`"
package: "`r BiocStyle::pkg_ver('NetworkHub')`"
vignette: >
  %\VignetteIndexEntry{networkhub_string}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}  
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.align = "center",
  fig.show = "asis",
  eval = TRUE,
  fig.width = 10,
  fig.height = 7,
  tidy = FALSE,
  message = FALSE,
  warning = FALSE,
  size = "small",
  echo = TRUE,
  results = "markup"
)

options(
  replace.assign = TRUE, 
  width = 100
)
```




# Session Info {-}

```{r}
sessionInfo()
```


<hr>

# References

